In [2]:
from mxnet import nd

In [3]:
nd.zeros((3,4))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [11]:
x = nd.ones((3,4))
x


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [5]:
nd.array([[1,2],[3,4]])


[[1. 2.]
 [3. 4.]]
<NDArray 2x2 @cpu(0)>

创建随机数组，下面创建均值为0，方差为1的正太分布

In [7]:
y = nd.random_normal(0,1,shape=(3,4))
y


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.558071   -0.5459446  -2.3556297 ]
 [ 0.54144025  2.6785064   1.2546344  -0.54877406]]
<NDArray 3x4 @cpu(0)>

In [8]:
y.shape

(3, 4)

In [9]:
# 它的大小，就是总元素个数，就是形状的累乘
y.size

12

In [13]:
x + y 


[[ 2.1630785   1.4838046   1.2995634   1.1530255 ]
 [-0.16881478  2.5580711   0.45405543 -1.3556297 ]
 [ 1.5414402   3.6785064   2.2546344   0.45122594]]
<NDArray 3x4 @cpu(0)>

In [14]:
x * y


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.558071   -0.5459446  -2.3556297 ]
 [ 0.54144025  2.6785064   1.2546344  -0.54877406]]
<NDArray 3x4 @cpu(0)>

In [10]:
nd.exp(y)


[[ 3.1997688   1.6222347   1.3492696   1.1653546 ]
 [ 0.31073502  4.7496505   0.5792943   0.09483377]
 [ 1.7184801  14.563325    3.506556    0.5776575 ]]
<NDArray 3x4 @cpu(0)>

In [12]:
nd.dot(x,y.T)


[[ 2.099472  -2.5123181  3.9258068]
 [ 2.099472  -2.5123181  3.9258068]
 [ 2.099472  -2.5123181  3.9258068]]
<NDArray 3x3 @cpu(0)>

### 广播

In [19]:
a = nd.arange(3).reshape((3,1)) 
b = nd.arange(2).reshape((1,2))
print('a', a)
print('b', b)
print('a+b', a+b)

a 
[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>
b 
[[0. 1.]]
<NDArray 1x2 @cpu(0)>
a+b 
[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>


### 与NUmpy的转换

In [21]:
import numpy as np

In [23]:
x = np.ones((2,3))
y = nd.array(x)
z = y.asnumpy()
print([z,y])

[array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32), 
[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>]


### 替换操作

在前面的样例中，我们为每个操作新开内存来储存它的结果。例如，如果我们写`y=x+y`,我们会把y从现在指向的实例转到新建的实例中去。

In [24]:
x = nd.ones((3,4))
y = nd.ones((3,4))

before = id(y)
y = y + x
id(y) == before

False

In [25]:
z = nd.zeros_like(x)
before = id(z)
z[:] = x + y
id(z) == before

True

但是这里我们还是为 `x+y`创建了临时空间，然后再复制到z.需要避免这个开销，我们可以使用操作符的全名版本中的out参数：

In [29]:
nd.elemwise_add(x, y, out=z)
id(z) ==before

True